version: '3.9'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest_with_spring_boot_udemy
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - woosh-network
  rest-with-spring-boot-udemy:
    image: wooshnp/rest-with-spring-boot-udemy
    restart: always
    build: ./rest-with-spring-boot-udemy
    working_dir: /rest-with-spring-boot-udemy
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC&useSSL=false
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - woosh-network
networks:
  erudio-network:
    driver: bridge